---
title: "Korea Map v3"
author: "coop711"
date: '2017 9 20 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Map Data


```{r cars}
library(maptools) #> `readShapePoly()`, `rgdal::readOGR()`로 대체
library(ggmap) #> `geocode()`, `ggmap()`, `qmap()`, `revgeocode()`
library(ggplot2) #> `ggplot()`
library(rgdal) #> `CRS`, `ogrInfo()`, `ogrListLayers()`, `readOGR()`, `spTransform()`
library(dplyr) #> `arrange()`, `filter()`, `group_by()`, `left_join()`, `mutate()`,  
library(broom)
getwd()
dsn <- "../data/CTPRVN_201703"
shp1 <- readOGR(dsn, 
                layer = "TL_SCCO_CTPRVN",
                stringsAsFactors = FALSE,
                encoding = "CP949")
# map1 <- fortify(shp1)
proj4string(shp1)
coordinates(shp1)
shp1_84 <- spTransform(shp1, CRS("+init=epsg:4326"))
coordinates(shp1_84)
map1 <- tidy(shp1_84)
shp1_84@data
shp1_84$AB_name <- c("서울", "부산", "대구", "인천", "광주", "대전", "율산", "세종", "경기", "강원", "충북", "충남", "전북", "전남", "경북", "경남", "제주")
shp1_84@data
str(map1)
dsn2 <- "../data/SIG_201703"
shp2 <- readOGR(dsn2, 
                layer = "TL_SCCO_SIG",
                stringsAsFactors = FALSE,
                encoding = "CP949")
map2 <- fortify(shp2)
nrow(map2)
dsn3 <- "../data/EMD_201703"
shp3 <- readOGR(dsn3, 
                layer = "TL_SCCO_EMD",
                stringsAsFactors = FALSE,
                encoding = "CP949")
map3 <- fortify(shp3)
nrow(map3)
dsn4 <- "../data/LI_201703"
shp4 <- readOGR(dsn4, 
                layer = "TL_SCCO_LI",
                stringsAsFactors = FALSE,
                encoding = "CP949")
map4 <- fortify(shp4)
nrow(map4)
```

## Plots

You can also embed plots, for example:

```{r maps, echo = FALSE, eva = FALSE}
library(RColorBrewer)
# fill.pal <- colorRampPalette(brewer.pal(8, "Accent"))(17)
# pie(rep(1, 17), col = fill.pal)
ggplot(data = map1, 
       mapping = aes(x = long,
                     y = lat,
                     group = group)) +
  geom_polygon(fill = "white",
               colour = "black") +
  coord_map() 
#  scale_fill_manual(values = fill.pal)
```

## Simplified

```{r}
shp_simp <- readOGR(dsn = "../data/TL_SCCO_CTPRVN", 
                    layer = "TL_SCCO_CTPRVN")
shp_simp@data
shp_simp@data <- shp1@data
shp_simp@data
summary(shp_simp)
ogrInfo(dsn = "../data/TL_SCCO_CTPRVN", 
                    layer = "TL_SCCO_CTPRVN")
proj4string(shp_simp)
coordinates(shp_simp)
shp_simp84 <- shp_simp %>% spTransform(CRS("+init=epsg:4326"))
coordinates(shp_simp84)
names(shp_simp84@data) <- c("code", "name_eng", "name_kor", "AB_name")
str(shp_simp84@data)
# geocode(shp_simp$name_eng)
map_simp <- tidy(shp_simp84)
str(map_simp)
shp_simp84$id <- rownames(shp_simp84@data)
shp_simp84@data
map_merged <- merge(map_simp, shp_simp84@data, by = "id")
map_merged$region <- map_merged$code
str(map_merged)
map_coords <- coordinates(shp_simp84)
colnames(map_coords) <- c("long", "lat")
map_coords
map_data <- cbind(map_coords, shp_simp84@data)
map_data
map_df <- left_join(map_simp, shp_simp84@data, c("id" = "id"))
map_df$name_kor_f <- factor(map_df$name_kor, 
                            levels = shp_simp84$name_kor, 
                            labels = shp_simp84$AB_name)
str(map_df)
Dokdo_coord <- geocode("Dokdo")
```

```{r}
ggplot(data = map_simp, 
       mapping = aes(x = long,
                     y = lat,
                     group = group)) +
  geom_polygon(fill = "white",
               colour = "black") +
  coord_map() +
  geom_text(data = map_data, 
            mapping = aes(x = long, 
                          y = lat,
                          label = AB_name),
            inherit.aes = FALSE,
            family = "HCR Dotum LVT",
            size = 4,
            colour = "blue") +
  theme(axis.title.x = element_text(family = "HCR Dotum LVT"),
        axis.title.y = element_text(family = "HCR Dotum LVT"),
        text = element_text(family = "HCR Dotum LVT")) +
  labs(x = "경도", y = "위도") +
  annotate("text", 
           x = Dokdo_coord$lon, 
           y = Dokdo_coord$lat, 
           label = "독도",
           family = "HCR Dotum LVT",
           colour = "red")
fill.pal <- colorRampPalette(brewer.pal(8, "Accent"))(17)
ggplot(data = map_df, 
       mapping = aes(x = long,
                     y = lat,
                     group = group,
                     fill = name_kor_f)) +
  geom_polygon() +
#  geom_polygon(fill = "white",
#               colour = "black") +
  coord_map() +
  theme(legend.text = element_text((family = "HCR Dotum LVT"))) +
  guides(fill = guide_legend(title = NULL)) +
  scale_fill_manual(name = "Province", values = fill.pal)
```